[package]
name = "test_constructor"
version = "21.5.0"
authors = ["Stellar Development Foundation <info@stellar.org>"]
license = "Apache-2.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
soroban-sdk = { version = "22.0.0-rc.2" }

[dev-dependencies]
soroban-sdk = { version = "22.0.0-rc.2", features = ["testutils"] }
